import { chmod, copyFile, cp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";
import { exec, checked, type ExecResult } from "./process";
import { OwnedContainerError, runOwnedContainer } from "./container";
import { TOOLHOST_SMOKE_SCRIPT } from "./toolhost";
import { readState, writeState } from "./state";
import type { ArmName, ArmResult, CommandEvidence, RunState } from "./types";

export interface RunOptions { runDir: string; authFile: string; dockerBin?: string; arm?: "current" }

const arms: ArmName[] = ["stock", "current"];
function progress(message: string): void { process.stderr.write(`[run] ${message}\n`); }

// Build only the ignored JavaScript embed that a clean checkout omits. Running
// the full go:generate target would also rewrite the tracked shared WASM.
const prepareRouterAssets = [
  "bun install --cwd plugins --frozen-lockfile",
  "git check-ignore -q internal/router/toolplugin/dist/tools.js",
  "wasm_before=$(sha256sum internal/router/toolplugin/shared_core.wasm | cut -d' ' -f1)",
  "bun build plugins/tools.ts --outfile ./internal/router/toolplugin/dist/tools.js --production --target node --format esm --external hpatch:core/v1 '--banner=// Code generated by Bun from plugins/tools.ts. DO NOT EDIT.'",
  "test -s internal/router/toolplugin/dist/tools.js",
  'test "$wasm_before" = "$(sha256sum internal/router/toolplugin/shared_core.wasm | cut -d\' \' -f1)"',
].join(" && ");

function containerArgs(state: RunState): string[] {
  return ["--cpus", state.resource_limits.cpus, "--memory", state.resource_limits.memory];
}

function imageRef(state: RunState): string { return state.image_id ?? state.image; }

async function setupArm(runDir: string, state: RunState, arm: ArmName, authFile: string): Promise<{ home: string; output: string; cache: string }> {
  const armRoot = join(runDir, "arms", arm);
  const home = join(armRoot, "home/ubuntu");
  const output = join(runDir, "artifacts", arm);
  const cache = join(armRoot, "go-cache");
  await cp(join(runDir, state.arms[arm].home_template), home, { recursive: true, force: false });
  await mkdir(join(home, ".codex"), { recursive: true, mode: 0o700 });
  await copyFile(authFile, join(home, ".codex/auth.json"));
  await chmod(home, 0o700);
  await chmod(join(home, ".codex"), 0o700);
  await chmod(join(home, ".codex/auth.json"), 0o600);
  await mkdir(output, { recursive: true });
  await mkdir(cache, { recursive: true });
  return { home, output, cache };
}

async function preflightChecks(docker: string, state: RunState, runDir: string, signal: AbortSignal): Promise<string> {
  const image = imageRef(state);
  const prefix = `codex-ab-${state.id}-preflight`;
  progress(`checking bare Codex image ${image}`);
  const check = await runOwnedContainer({ docker, name: `${prefix}-image`, signal, createArgs: [image, "sh", "-lc", "printf 'codex_path=%s\\n' \"$(command -v codex || true)\"; if command -v hpatch >/dev/null; then printf 'hpatch_path=%s\\n' \"$(command -v hpatch)\"; exit 8; fi; codex --version"] });
  if (check.exitCode !== 0) throw new Error(`image is not a bare Codex image (${check.exitCode}): ${[check.stdout.trim(), check.stderr.trim()].filter(Boolean).join("; ")}`);
  if (!check.stdout.includes("codex_path=/usr/local/bin/codex")) throw new Error(`image Codex is not the direct /usr/local/bin/codex entry: ${check.stdout.trim()}`);
  if (!check.stdout.includes(state.runtime_tools.codex_version)) throw new Error(`unexpected container Codex version: ${check.stdout.trim()}`);
  const identity = await runOwnedContainer({ docker, name: `${prefix}-identity`, signal, createArgs: [image, "sh", "-lc", "printf '%s:%s\\n' \"$(id -u)\" \"$(id -g)\""] });
  const expectedIdentity = `${state.operator.uid}:${state.operator.gid}`;
  if (identity.exitCode !== 0 || identity.stdout.trim() !== expectedIdentity) throw new Error(`container operator identity must be ${expectedIdentity}, got ${identity.stdout.trim()}`);
  const binaryHash = await runOwnedContainer({ docker, name: `${prefix}-hash`, signal, createArgs: [image, "sha256sum", "/usr/local/bin/codex", "/usr/local/bin/codex-code-mode-host"] });
  const hashes = binaryHash.stdout.trim().split("\n").map(line => line.trim().split(/\s+/)[0]);
  if (binaryHash.exitCode !== 0 || hashes[0] !== state.runtime_tools.codex_sha256 || hashes[1] !== state.runtime_tools.codex_code_mode_host_sha256) {
    throw new Error(`container Codex hash differs from prepared source: ${binaryHash.stdout.trim()}`);
  }
  progress("exercising the local code-mode host protocol without model access");
  const toolHost = await runOwnedContainer({ docker, name: `${prefix}-toolhost`, signal, timeoutMs: 15_000, createArgs: ["--network", "none", image, "node", "-e", TOOLHOST_SMOKE_SCRIPT] });
  if (toolHost.exitCode !== 0 || toolHost.stdout.trim() !== "CODEX_AB_TOOL_HOST_OK") throw new Error(`code-mode tool host smoke failed: ${[toolHost.stdout.trim(), toolHost.stderr.trim()].filter(Boolean).join("; ")}`);
  const currentHome = resolve(runDir, state.arms.current.home_template);
  const workspace = resolve(runDir, state.arms.current.repository);
  progress("checking snapshotted skills and registered Go hook offline");
  const hookEvent = JSON.stringify({ hook_event_name: "PostToolUse", cwd: "/workspace", tool_input: { cmd: "skills-mgr get golang-best-practices" }, tool_response: { exit_code: 0 } });
  const dependencies = await runOwnedContainer({ docker, name: `${prefix}-setup`, signal, createArgs: ["--network", "none", "-v", `${currentHome}:/setup:ro`, "-v", `${workspace}:/workspace:ro`, image,
    "sh", "-lc", `cp -a /setup/. /home/ubuntu/ && export PATH=/home/ubuntu/.local/bin:/usr/local/bin:/usr/bin:/bin && test -r /home/ubuntu/.codex/config.toml && : >/home/ubuntu/.codex/.write-check && rm /home/ubuntu/.codex/.write-check && skills-mgr list >/dev/null && rtk --version >/dev/null && test -x /home/ubuntu/.codex/hooks/bin/session_start_context && test \"$(skills-mgr get use-modern-go/scripts/VERSION)\" = v0.1.1 && skills-mgr get use-modern-go >/tmp/use-modern-go && test \"$(wc -c </tmp/use-modern-go)\" -gt 224 && grep -q 'Modern Go Guidelines CLI' /tmp/use-modern-go && printf '%s\\n' '${hookEvent}' | /home/ubuntu/.codex/hooks/bin/go_guidelines | grep -q 'Modern Go Guidelines v0.1.1: /workspace/go.mod.*END_GO_GUIDELINES sha256='`] });
  if (dependencies.exitCode !== 0) throw new Error(`current setup cannot run offline unchanged in the container: ${[dependencies.stdout.trim(), dependencies.stderr.trim()].filter(Boolean).join("; ")}`);
  progress("compiling the exact base with installed plugin dependencies in an ephemeral container");
  const bun = resolve(runDir, state.runtime_tools.bun);
  const compile = await runOwnedContainer({ docker, name: `${prefix}-compile`, signal, timeoutMs: 10 * 60 * 1000, createArgs: ["--cpus", state.resource_limits.cpus, "--memory", state.resource_limits.memory,
    "-v", `${resolve(runDir, "seed.git")}:/seed:ro`, "-v", `${bun}:/usr/local/bin/bun:ro`, image, "sh", "-lc",
    `git clone --no-hardlinks /seed /tmp/preflight >/dev/null && git -C /tmp/preflight checkout ${state.source.base_commit} >/dev/null && cd /tmp/preflight && ${prepareRouterAssets} && git diff --quiet HEAD -- && go test ./internal/router -run '^$'`] });
  if (compile.exitCode !== 0) throw new Error(`base dependency/compile preflight failed: ${compile.stderr.trim()}`);
  const inspected = await exec([docker, "image", "inspect", "--format", "{{.Id}}", image]);
  const imageId = inspected.stdout.trim();
  if (inspected.exitCode !== 0 || !/^sha256:[0-9a-f]{64}$/.test(imageId)) throw new Error(`cannot resolve immutable image ID for ${image}: ${inspected.stderr.trim()}`);
  if (state.image_id && imageId !== state.image_id) throw new Error(`prepared image changed: expected ${state.image_id}, got ${imageId}`);
  progress("preflight passed without model inference");
  return imageId;
}

async function preflight(docker: string, state: RunState, runDir: string): Promise<string> {
  const controller = new AbortController();
  const cancel = () => controller.abort();
  process.once("SIGINT", cancel);
  process.once("SIGTERM", cancel);
  try {
    const imageId = await preflightChecks(docker, state, runDir, controller.signal);
    if (controller.signal.aborted) throw new Error("preflight canceled; no model was launched");
    return imageId;
  } finally {
    process.removeListener("SIGINT", cancel);
    process.removeListener("SIGTERM", cancel);
  }
}

export async function preflightRun(runDirectory: string, dockerBin = process.env.CODEX_AB_DOCKER_BIN ?? "docker"): Promise<void> {
  const runDir = resolve(runDirectory);
  const state = await readState(runDir);
  if (state.status !== "prepared") throw new Error(`preflight requires a prepared run, got ${state.status}`);
  state.image_id = await preflight(dockerBin, state, runDir);
  await writeState(runDir, state);
}

async function prewarm(docker: string, runDir: string, state: RunState, arm: ArmName, home: string, cache: string, signal: AbortSignal): Promise<void> {
  const name = `codex-ab-${state.id}-${arm}-warm`;
  const repo = resolve(runDir, state.arms[arm].repository);
  const bun = resolve(runDir, state.runtime_tools.bun);
  const result = await runOwnedContainer({ docker, name, signal, createArgs: [...containerArgs(state), "-v", `${repo}:/workspace`, "-v", `${home}:/home/ubuntu`, "-v", `${cache}:/home/ubuntu/.cache/go-build`, "-v", `${bun}:/usr/local/bin/bun:ro`,
    imageRef(state), "sh", "-lc", `${prepareRouterAssets} && go test ./internal/router -run '^$'`] });
  if (result.exitCode !== 0) throw new Error(`${arm} cache prewarm failed: ${result.stderr.trim()}`);
  const dirty = await exec(["git", "-C", repo, "status", "--porcelain", "--untracked-files=normal"]);
  if (dirty.exitCode !== 0 || dirty.stdout.trim()) throw new Error(`${arm} prewarm changed the immutable baseline: ${dirty.stdout.trim() || dirty.stderr.trim()}`);
}

export async function changedFiles(repository: string, baseCommit: string): Promise<string[]> {
  const [tracked, untracked] = await Promise.all([
    checked(["git", "-C", repository, "diff", "--name-only", baseCommit]),
    checked(["git", "-C", repository, "ls-files", "--others", "--exclude-standard"]),
  ]);
  return [...new Set([...tracked.stdout.split("\n"), ...untracked.stdout.split("\n")].filter(Boolean))].sort();
}

export async function capturePatch(repository: string, baseCommit: string, target: string): Promise<void> {
  await checked(["git", "-C", repository, "add", "--intent-to-add", "--all", "--", "."]);
  const result = await exec(["git", "-C", repository, "diff", "--binary", baseCommit], { stdoutFile: target });
  if (result.exitCode !== 0) throw new Error(`could not capture patch: ${result.stderr.trim()}`);
}

function evidence(command: string, started: Date, result: Awaited<ReturnType<typeof exec>>): CommandEvidence {
  return { command, started_at: started.toISOString(), elapsed_ms: result.elapsedMs, exit_code: result.exitCode, stdout: result.stdout, stderr: result.stderr };
}

async function gradeArm(docker: string, runDir: string, state: RunState, arm: ArmName, patchPath: string, signal: AbortSignal): Promise<ArmResult["grade"]> {
  if (!state.acceptance) return undefined;
  const evaluator = join(runDir, "evaluator", arm);
  await checked(["git", "clone", "--no-local", "--no-hardlinks", join(runDir, "seed.git"), evaluator]);
  await checked(["git", "-C", evaluator, "checkout", state.source.base_commit]);
  const patchStat = await Bun.file(patchPath).size;
  if (patchStat > 0) await checked(["git", "-C", evaluator, "apply", "--binary", patchPath]);
  await copyFile(join(runDir, state.acceptance.path), join(evaluator, "internal/router/ab_acceptance_test.go"));
  const gradeStarted = performance.now();
  const bun = resolve(runDir, state.runtime_tools.bun);
  const cache = resolve(runDir, "arms", arm, "go-cache");
  let started = new Date();
  const preparationResult = await runOwnedContainer({ docker, name: `codex-ab-${state.id}-${arm}-grade-prepare`, signal, createArgs: [...containerArgs(state), "-v", `${resolve(evaluator)}:/workspace`, "-v", `${cache}:/home/ubuntu/.cache/go-build`, "-v", `${bun}:/usr/local/bin/bun:ro`, imageRef(state), "sh", "-lc", prepareRouterAssets] });
  const preparation = evidence("install locked plugins and build ignored tools.js embed", started, preparationResult);
  if (preparation.exit_code !== 0 || signal.aborted) {
    const skipped = { command: "not run", started_at: new Date().toISOString(), elapsed_ms: 0, exit_code: -1, stdout: "", stderr: signal.aborted ? "grading canceled" : "grading preparation failed" };
    return { preparation, acceptance: skipped, router_suite: skipped, elapsed_ms: Math.round(performance.now() - gradeStarted), passed: false };
  }
  const base = [...containerArgs(state), "-v", `${resolve(evaluator)}:/workspace`, "-v", `${cache}:/home/ubuntu/.cache/go-build`, imageRef(state)];
  started = new Date();
  const acceptanceResult = await runOwnedContainer({ docker, name: `codex-ab-${state.id}-${arm}-grade`, signal, createArgs: [...base, "go", "test", "./internal/router", "-run", "^TestABAcceptance", "-count=1"] });
  const acceptance = evidence("go test ./internal/router -run '^TestABAcceptance' -count=1", started, acceptanceResult);
  if (signal.aborted) {
    const skipped = { command: "not run", started_at: new Date().toISOString(), elapsed_ms: 0, exit_code: -1, stdout: "", stderr: "grading canceled" };
    return { preparation, acceptance, router_suite: skipped, elapsed_ms: Math.round(performance.now() - gradeStarted), passed: false };
  }
  started = new Date();
  const suiteResult = await runOwnedContainer({ docker, name: `codex-ab-${state.id}-${arm}-grade-suite`, signal, createArgs: [...base, "go", "test", "./internal/router"] });
  const routerSuite = evidence("go test ./internal/router", started, suiteResult);
  return { preparation, acceptance, router_suite: routerSuite, elapsed_ms: Math.round(performance.now() - gradeStarted), passed: preparation.exit_code === 0 && acceptance.exit_code === 0 && routerSuite.exit_code === 0 };
}

async function runArm(docker: string, runDir: string, state: RunState, arm: ArmName, home: string, output: string, cache: string, task: string, signal: AbortSignal): Promise<ArmResult> {
  const name = `codex-ab-${state.id}-${arm}`;
  const repository = resolve(runDir, state.arms[arm].repository);
  const stdoutPath = join(output, "codex.jsonl");
  const stderrPath = join(output, "codex.stderr");
  const patchPath = join(output, "changes.patch");
  const started = new Date();
  progress(`${arm}: agent started`);
  let result: ExecResult | undefined;
  let lifecycleError: string | undefined;
  try {
    result = await runOwnedContainer({ docker, name, signal, stdin: task, stdoutFile: stdoutPath, stderrFile: stderrPath, timeoutMs: state.timeout_seconds * 1000, createArgs: [...containerArgs(state), "-i", "-e", "PATH=/home/ubuntu/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/go/bin",
      "-v", `${repository}:/workspace`, "-v", `${home}:/home/ubuntu`, "-v", `${output}:/output`, "-v", `${cache}:/home/ubuntu/.cache/go-build`,
      imageRef(state), "codex", "exec", "--json", "--color", "never", "--dangerously-bypass-hook-trust", "-C", "/workspace", "--model", state.execution.model,
      "-c", `model_reasoning_effort=${JSON.stringify(state.execution.reasoning_effort)}`, "-c", `service_tier=${JSON.stringify(state.execution.service_tier)}`, "-c", 'approval_policy="never"', "-c", 'sandbox_mode="danger-full-access"', "-"] });
  } catch (error) {
    lifecycleError = error instanceof Error ? error.message : String(error);
    if (error instanceof OwnedContainerError && error.result) result = error.result;
  }
  const finishedAt = new Date().toISOString();
  progress(`${arm}: agent stopped after ${Math.round((result?.elapsedMs ?? 0) / 1000)}s${lifecycleError ? ` (${lifecycleError})` : ""}`);
  return {
    arm,
    anonymous_id: arm === "stock" ? "candidate-1" : "candidate-2",
    container: name,
    started_at: started.toISOString(),
    finished_at: finishedAt,
    agent_elapsed_ms: result?.elapsedMs ?? 0,
    exit_code: result?.exitCode ?? -1,
    timed_out: result?.timedOut ?? false,
    canceled: result?.canceled === true || signal.aborted,
    patch_path: patchPath.slice(runDir.length + 1),
    stdout_path: stdoutPath.slice(runDir.length + 1),
    stderr_path: stderrPath.slice(runDir.length + 1),
    changed_files: [],
    head_after_agent: "",
    lifecycle_error: lifecycleError,
  };
}

async function collectArm(runDir: string, state: RunState, arm: ArmName, result: ArmResult): Promise<void> {
  const repository = resolve(runDir, state.arms[arm].repository);
  const patchPath = join(runDir, result.patch_path);
  try {
    result.changed_files = await changedFiles(repository, state.source.base_commit);
    await capturePatch(repository, state.source.base_commit, patchPath);
    result.head_after_agent = (await checked(["git", "-C", repository, "rev-parse", "HEAD"])).stdout.trim();
  } catch (error) {
    result.collection_error = error instanceof Error ? error.message : String(error);
    await writeFile(patchPath, "");
    progress(`${arm}: inference evidence persisted but patch collection failed: ${result.collection_error}`);
  }
}

export async function runPair(options: RunOptions): Promise<RunState> {
  const runDir = resolve(options.runDir);
  const state = await readState(runDir);
  if (state.status !== "prepared") throw new Error(`run is ${state.status}; prepare a new run instead of resuming or restarting it`);
  if (!state.acceptance) throw new Error("run has no evaluator acceptance test; prepare with --acceptance");
  const docker = options.dockerBin ?? process.env.CODEX_AB_DOCKER_BIN ?? "docker";
  state.image_id = await preflight(docker, state, runDir);
  await writeState(runDir, state);
  const controller = new AbortController();
  const selectedArms: ArmName[] = options.arm ? [options.arm] : arms;
  const cancel = () => controller.abort();
  process.once("SIGINT", cancel);
  process.once("SIGTERM", cancel);
  try {
    const auth = resolve(options.authFile);
    const authMode = (await import("node:fs/promises")).stat(auth).then(s => s.mode & 0o777);
    if ((await authMode) & 0o077) throw new Error("auth file must not be accessible by group or others (expected mode 0600)");
    const setupResults = await Promise.allSettled(selectedArms.map(async arm => [arm, await setupArm(runDir, state, arm, auth)] as const));
    const setupFailure = setupResults.find(result => result.status === "rejected");
    if (setupFailure?.status === "rejected") throw setupFailure.reason;
    const setups = Object.fromEntries(setupResults.map(result => (result as PromiseFulfilledResult<readonly [ArmName, Awaited<ReturnType<typeof setupArm>>]>).value)) as Partial<Record<ArmName, Awaited<ReturnType<typeof setupArm>>>>;
    if (controller.signal.aborted) throw new Error("canceled during private arm setup; no model was launched");
    state.status = "running";
    state.results = {};
    state.selected_arms = selectedArms;
    await writeState(runDir, state);
    progress(options.arm ? "prewarming the selected current arm" : "prewarming identical Go targets for both arms");
    const warmed = await Promise.allSettled(selectedArms.map(arm => prewarm(docker, runDir, state, arm, setups[arm]!.home, setups[arm]!.cache, controller.signal)));
    const warmFailure = warmed.find(result => result.status === "rejected");
    if (warmFailure?.status === "rejected") throw warmFailure.reason;
    if (controller.signal.aborted) throw new Error("canceled during dependency prewarm; no agent was launched");
    const task = await readFile(join(runDir, state.task.path), "utf8");
    if (controller.signal.aborted) throw new Error("canceled while reading the task; no agent was launched");
    for (const arm of selectedArms) {
      const repo = resolve(runDir, state.arms[arm].repository);
      const dirty = await exec(["git", "-C", repo, "status", "--porcelain", "--untracked-files=normal"]);
      if (dirty.exitCode !== 0 || dirty.stdout.trim()) throw new Error(`${arm} baseline changed before model launch: ${dirty.stdout.trim() || dirty.stderr.trim()}`);
    }
    const launchTime = new Date().toISOString();
    state.arm_attempts = Object.fromEntries(selectedArms.map(arm => [arm, {
      codex_home: `arms/${arm}/home/ubuntu/.codex`,
      container: `codex-ab-${state.id}-${arm}`,
      started_at: launchTime,
      status: "started",
    }])) as RunState["arm_attempts"];
    await writeState(runDir, state);
    const settled = await Promise.allSettled(selectedArms.map(arm => runArm(docker, runDir, state, arm, setups[arm]!.home, setups[arm]!.output, setups[arm]!.cache, task, controller.signal)));
    settled.forEach((item, index) => {
      const arm = selectedArms[index]!;
      const attempt = state.arm_attempts![arm]!;
      attempt.finished_at = new Date().toISOString();
      if (item.status === "fulfilled") state.results![arm] = item.value;
      else {
        attempt.status = "failed";
        attempt.error = String(item.reason);
        const message = `${arm}: failed to collect result: ${String(item.reason)}`;
        state.error = state.error ? `${state.error}; ${message}` : message;
        progress(message);
      }
      if (item.status === "fulfilled") attempt.status = "stopped";
    });
    await writeState(runDir, state);
    const collected = await Promise.allSettled(selectedArms.map(async arm => {
      const result = state.results?.[arm];
      if (result && !result.lifecycle_error) await collectArm(runDir, state, arm, result);
    }));
    const collectionFailure = collected.find(result => result.status === "rejected");
    if (collectionFailure?.status === "rejected") state.error = String(collectionFailure.reason);
    await writeState(runDir, state);
    if (!controller.signal.aborted && selectedArms.every(arm => state.results?.[arm] && !state.results[arm]!.lifecycle_error && !state.results[arm]!.collection_error)) {
      progress(`${options.arm ? "selected agent" : "both agents"} stopped; starting evaluator-only grading`);
      const graded = await Promise.allSettled(selectedArms.map(async arm => {
        const result = state.results![arm]!;
        result.grade = await gradeArm(docker, runDir, state, arm, join(runDir, result.patch_path), controller.signal);
        progress(`${arm}: grading ${result.grade ? (result.grade.passed ? "passed" : "failed") : "not configured"}`);
      }));
      const gradeFailure = graded.find(result => result.status === "rejected");
      if (gradeFailure?.status === "rejected") throw gradeFailure.reason;
    }
    for (const result of Object.values(state.results)) {
      if (result?.collection_error) state.error = state.error ? `${state.error}; ${result.collection_error}` : result.collection_error;
    }
    state.status = !controller.signal.aborted && selectedArms.every(arm => state.results?.[arm] && !state.results[arm]!.lifecycle_error && !state.results[arm]!.collection_error && state.results[arm]!.grade) ? "complete" : "partial";
    await writeState(runDir, state);
    return state;
  } catch (error) {
    state.status = "partial";
    state.error = error instanceof Error ? error.message : String(error);
    await writeState(runDir, state);
    throw error;
  } finally {
    process.removeListener("SIGINT", cancel);
    process.removeListener("SIGTERM", cancel);
  }
}
