import { chmod, copyFile, cp, lstat, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { exec, checked, type ExecResult } from "./process";
import { OwnedContainerError, runOwnedContainer } from "./container";
import { initializeSubmodules, verifyGodoxyIdentity, verifyPreparedInputs } from "./prepare";
import { acceptanceExecutionError, acceptanceTestNames, evaluatorCompatibilityError } from "./grading";
import candidateSource from "./candidate-script.txt" with { type: "text" };
import { executorOwnership, protectedArgs, protectedPreflight } from "./isolation";
import { TOOLHOST_SMOKE_SCRIPT } from "./toolhost";
import { readState, writeState, withRunLock } from "./state";
import type { ArmName, ArmResult, CommandEvidence, RunState } from "./types";

export interface RunOptions { runDir: string; authFile: string; dockerBin?: string; arm?: ArmName; signal?: AbortSignal }

const arms: ArmName[] = ["stock", "current"];
function progress(message: string): void { process.stderr.write(`[run] ${message}\n`); }

// Build only the ignored JavaScript embed that a clean checkout omits. Running
// the full go:generate target would also rewrite the tracked shared WASM.
const prepareRouterAssets = [
  "bun install --cwd plugins --frozen-lockfile",
  "git check-ignore -q internal/router/toolplugin/dist/tools.js",
  "wasm_before=$(sha256sum internal/router/toolplugin/shared_core.wasm | cut -d' ' -f1)",
  "bun build plugins/tools.ts --outfile ./internal/router/toolplugin/dist/tools.js --production --target node --format esm --external hpatch:core/v1 --external mekugi:core/v1 '--banner=// Code generated by Bun from plugins/tools.ts. DO NOT EDIT.'",
  "test -s internal/router/toolplugin/dist/tools.js",
  'test "$wasm_before" = "$(sha256sum internal/router/toolplugin/shared_core.wasm | cut -d\' \' -f1)"',
].join(" && ");

const iconsPackage = "./internal/homepage/icons/fetch";
const iconsGoCheck = String.raw`go version && go env GOVERSION | awk -F. '{ sub(/^go/, "", $1); if ($1 !~ /^[0-9]+$/ || $2 !~ /^[0-9]+$/ || $1 < 1 || ($1 == 1 && $2 < 27)) exit 1 }'`;
const iconsCompile = `go test -count=1 -ldflags=-checklinkname=0 -run '^$' ${iconsPackage}`;

function testPackage(state: RunState): string {
  return state.profile === "skills-mgr-bundle" ? "." : "./internal/router";
}

function prepareAssets(state: RunState): string {
  return state.criteria?.contract.preparation ?? (state.profile === "skills-mgr-bundle" ? "go version" : prepareRouterAssets);
}

function acceptanceTarget(state: RunState): string {
  if (state.profile === "skills-mgr-bundle") return "ab_acceptance_test.go";
  return state.profile === "godoxy-icons"
    ? "internal/homepage/icons/fetch/ab_acceptance_test.go"
    : "internal/router/ab_acceptance_test.go";
}

const iconsTest = `go test -count=1 -ldflags=-checklinkname=0 ${iconsPackage}`;

function containerArgs(state: RunState): string[] {
  return ["--cpus", state.resource_limits.cpus, "--memory", state.resource_limits.memory];
}

function currentSetupMounts(runDir: string, state: RunState, arm: ArmName = "current"): string[] {
  if (arm !== "current" && state.comparison !== "same-setup") return [];
  return ["-v", `${resolve(runDir, state.runtime_tools.current_setup_installs)}:/home/ubuntu/.local/share/mise/installs:ro`];
}

function imageRef(state: RunState): string { return state.image_id ?? state.image; }

async function inspectCandidate(docker: string, runDir: string, state: RunState, repository: string, label: string,
  signal: AbortSignal, baseline: boolean, clean: boolean, capture?: string): Promise<void> {
  const spec = { mode: capture ? "capture" : "verify", baseline, clean, base: state.source.base_commit,
    tree: state.source.base_tree, forbidden: state.source.forbidden_commit, icons: state.profile === "godoxy-icons", submodules: state.submodules ?? [] };
  const result = await runOwnedContainer({ docker, name: `codex-ab-${state.id}-${label}`, signal, timeoutMs: 60_000,
    createArgs: [...containerArgs(state), "--network", "none", "-e", "GIT_OPTIONAL_LOCKS=0", "-v", `${repository}:/workspace${capture ? "" : ":ro"}`,
      "-v", `${resolve(runDir, state.runtime_tools.bun)}:/usr/local/bin/bun:ro`, ...(capture ? ["-v", `${capture}:/capture`] : []),
      imageRef(state), "bun", "-e", candidateSource, JSON.stringify(spec)] });
  if (result.exitCode !== 0 || result.timedOut || result.canceled) throw new Error(`candidate ${label} verification failed: ${result.stderr.trim()}`);
}

async function setupArm(runDir: string, state: RunState, arm: ArmName, authFile: string): Promise<{ home: string; output: string; cache: string; moduleCache: string }> {
  const armRoot = join(runDir, "arms", arm);
  const home = join(armRoot, "home/ubuntu");
  const output = join(runDir, "artifacts", arm);
  const moduleCache = join(armRoot, "go-pkg-cache");
  const cache = join(armRoot, "go-cache");
  await cp(join(runDir, state.arms[arm].home_template), home, { recursive: true, force: false });
  await mkdir(join(home, ".codex"), { recursive: true, mode: 0o700 });
  await copyFile(authFile, join(home, ".codex/auth.json"));
  await chmod(home, 0o700);
  await chmod(join(home, ".codex"), 0o700);
  await mkdir(join(home, "go/pkg"), { recursive: true });
  await mkdir(join(home, ".local/share/mise/installs"), { recursive: true });
  await mkdir(join(home, ".bun/install/cache"), { recursive: true });
  await chmod(join(home, ".codex/auth.json"), 0o600);
  await mkdir(output, { recursive: true });
  await mkdir(moduleCache, { recursive: true });
  await mkdir(cache, { recursive: true });
  return { home, output, cache, moduleCache };
}

async function preflightChecks(docker: string, state: RunState, runDir: string, signal: AbortSignal): Promise<string> {
  await verifyPreparedInputs(runDir, state);
  if (state.profile === "godoxy-icons") verifyGodoxyIdentity(state.source, state.submodules);
  // Resolve the mutable tag before any checks, so every check and launch uses
  // the same image even if another process retags the operator's image.
  const inspected = await exec([docker, "image", "inspect", "--format", "{{.Id}}", imageRef(state)]);
  const image = inspected.stdout.trim();
  if (inspected.exitCode !== 0 || !/^sha256:[0-9a-f]{64}$/.test(image)) throw new Error("cannot resolve immutable image ID");
  if (state.image_id && image !== state.image_id) throw new Error("prepared image changed");
  state.image_id = image;
  for (const arm of arms) await inspectCandidate(docker, runDir, state, resolve(runDir, state.arms[arm].repository), `preflight-${arm}-baseline`, signal, true, true);
  const prefix = `codex-ab-${state.id}-preflight`;
  progress(`checking bare Codex image ${image}`);
  const check = await runOwnedContainer({ docker, name: `${prefix}-image`, signal, createArgs: [image, "sh", "-lc", "printf 'codex_path=%s\\n' \"$(command -v codex || true)\"; if command -v hpatch >/dev/null || command -v mekugi >/dev/null; then printf 'mekugi_path=%s\\n' \"$(command -v mekugi)\"; exit 8; fi; codex --version"] });
  if (check.exitCode !== 0) throw new Error(`image is not a bare Codex image (${check.exitCode}): ${[check.stdout.trim(), check.stderr.trim()].filter(Boolean).join("; ")}`);
  if (!check.stdout.includes("codex_path=/usr/local/bin/codex")) throw new Error(`image Codex is not the direct /usr/local/bin/codex entry: ${check.stdout.trim()}`);
  if (!check.stdout.includes(state.runtime_tools.codex_version)) throw new Error(`unexpected container Codex version: ${check.stdout.trim()}`);
  const identity = await runOwnedContainer({ docker, name: `${prefix}-identity`, signal, createArgs: [image, "sh", "-lc", "printf '%s:%s\\n' \"$(id -u)\" \"$(id -g)\""] });
  const expectedIdentity = `${state.operator.uid}:${state.operator.gid}`;
  if (identity.exitCode !== 0 || identity.stdout.trim() !== expectedIdentity) throw new Error(`container operator identity must be ${expectedIdentity}, got ${identity.stdout.trim()}`);
  const binaryHash = await runOwnedContainer({ docker, name: `${prefix}-hash`, signal, createArgs: [image, "sha256sum", "/usr/local/bin/codex", "/usr/local/bin/codex-code-mode-host", ...(state.protected_runtime ? ["/usr/local/libexec/codex-real"] : [])] });
  const hashes = binaryHash.stdout.trim().split("\n").map(line => line.trim().split(/\s+/)[0]);
  if (binaryHash.exitCode !== 0 || hashes[0] !== state.runtime_tools.codex_sha256 || hashes[1] !== state.runtime_tools.codex_code_mode_host_sha256 || (state.protected_runtime && hashes[2] !== state.runtime_tools.codex_sha256)) {
    throw new Error(`container Codex hash differs from prepared source: ${binaryHash.stdout.trim()}`);
  }
  progress("exercising the local code-mode host protocol without model access");
  const toolHost = await runOwnedContainer({ docker, name: `${prefix}-toolhost`, signal, timeoutMs: 15_000, createArgs: ["--network", "none", image, "node", "-e", TOOLHOST_SMOKE_SCRIPT] });
  if (toolHost.exitCode !== 0 || toolHost.stdout.trim() !== "CODEX_AB_TOOL_HOST_OK") throw new Error(`code-mode tool host smoke failed: ${[toolHost.stdout.trim(), toolHost.stderr.trim()].filter(Boolean).join("; ")}`);
  const currentHome = resolve(runDir, state.arms.current.home_template);
  const workspace = resolve(runDir, state.arms.current.repository);
  progress("checking the complete current setup and registered Go hook offline");
  const hookEvent = JSON.stringify({ hook_event_name: "PostToolUse", cwd: "/workspace", tool_input: { cmd: "skills-mgr get golang-best-practices" }, tool_response: { exit_code: 0 } });
  const mekugiCheck = state.execution.current_launcher === "mekugi"
    ? " && test -x /home/ubuntu/.local/bin/mekugi && test \"$(command -v shell)\" = /home/ubuntu/.local/bin/shell && (env -u MEKUGI_RUNTIME_DIR -u CODEX_THREAD_ID shell >/tmp/codex-ab-shell.stdout 2>/tmp/codex-ab-shell.stderr; test \"$?\" = 1) && grep -Fxq 'shell: CODEX_THREAD_ID is unavailable' /tmp/codex-ab-shell.stderr"
    : "";
  const dependencies = await runOwnedContainer({ docker, name: `${prefix}-setup`, signal, createArgs: ["--network", "none", "-e", `CODEX_AB_HOOK_EVENT=${hookEvent}`,
    "-v", `${currentHome}:/setup:ro`, "-v", `${workspace}:/workspace:ro`, ...currentSetupMounts(runDir, state), image, "sh", "-lc",
    `cp -a /setup/. /home/ubuntu/ && export PATH=/home/ubuntu/.local/bin:/usr/local/bin:/usr/bin:/bin && test -r /home/ubuntu/.codex/config.toml && : >/home/ubuntu/.codex/.write-check && rm /home/ubuntu/.codex/.write-check && cd /home/ubuntu && test -z "$(mise ls --current --missing --no-header)" && cd /workspace && mise exec -- sh -lc 'skills-mgr list >/dev/null && rtk --version >/dev/null && test -x /home/ubuntu/.codex/hooks/bin/session_start_context && test "$(skills-mgr get use-modern-go/scripts/VERSION)" = v0.1.1 && skills-mgr get use-modern-go >/tmp/use-modern-go && test "$(wc -c </tmp/use-modern-go)" -gt 224 && grep -q "Modern Go Guidelines CLI" /tmp/use-modern-go && if test -f /workspace/go.mod; then printf "%s\n" "$CODEX_AB_HOOK_EVENT" | /home/ubuntu/.codex/hooks/bin/go_guidelines | grep -q "Modern Go Guidelines v0.1.1: /workspace/go.mod.*END_GO_GUIDELINES sha256="; fi'${mekugiCheck}`] });
  if (/\[WARN\] migrate:/.test(`${dependencies.stdout}\n${dependencies.stderr}`)) {
    throw new Error("current setup mise migration failed against the read-only tool snapshot; prepare again from a home with completed mise migrations");
  }
  if (dependencies.exitCode !== 0) throw new Error(`current setup cannot run offline unchanged in the container: ${[dependencies.stdout.trim(), dependencies.stderr.trim()].filter(Boolean).join("; ")}`);
  if (state.execution.current_launcher === "mekugi") {
    progress("checking selected Mekugi flags and exports offline without model access");
    const launch = await runOwnedContainer({ docker, name: `${prefix}-mekugi`, signal, timeoutMs: 30000,
      createArgs: ["--network", "none", "-v", `${currentHome}:/setup:ro`, image, "sh", "-lc",
        'cp -a /setup/. /home/ubuntu/ && export PATH=/home/ubuntu/.local/bin:/usr/local/bin:/usr/bin:/bin && mekugi "$@" --capture-output=/tmp/capture.jsonl --metrics-output=/tmp/metrics.json codex --version',
        "preflight", ...(state.mekugi_flags ?? [])] });
    await writeFile(join(runDir, "artifacts/preflight-mekugi.json"), JSON.stringify(launch, null, 2));
    if (launch.exitCode !== 0) throw new Error(`selected Mekugi launcher failed before inference: ${launch.stderr.trim()}`);
  }
  if (state.profile !== "godoxy-icons") {
    progress("compiling the exact base and task dependencies in an ephemeral container");
    const bun = resolve(runDir, state.runtime_tools.bun);
    const preflightCache = state.runtime_tools.preflight_cache;
    const cacheArgs = preflightCache ? [
      ...(state.profile === "skills-mgr-bundle" || preflightCache.bun ? ["--network", "none"] : []),
      "-v", `${resolve(runDir, preflightCache.go_build)}:/home/ubuntu/.cache/go-build`,
      "-v", `${resolve(runDir, preflightCache.go_pkg)}:/home/ubuntu/go/pkg`,
      ...(preflightCache.bun ? ["-v", `${resolve(runDir, preflightCache.bun)}:/home/ubuntu/.bun/install/cache`] : []),
    ] : [];
    const compile = await runOwnedContainer({ docker, name: `${prefix}-compile`, signal, timeoutMs: 10 * 60 * 1000, createArgs: ["--cpus", state.resource_limits.cpus, "--memory", state.resource_limits.memory, ...cacheArgs,
      "-v", `${resolve(runDir, "seed.git")}:/seed:ro`, "-v", `${bun}:/usr/local/bin/bun:ro`, image, "sh", "-lc",
      `git clone --no-hardlinks /seed /tmp/preflight >/dev/null && git -C /tmp/preflight checkout ${state.source.base_commit} >/dev/null && cd /tmp/preflight && ${prepareAssets(state)} && git diff --quiet HEAD -- && ${state.criteria ? "true" : `go test ${testPackage(state)} -run '^$'`}`] });
    if (compile.exitCode !== 0) throw new Error(`base dependency/compile preflight failed: ${compile.stderr.trim()}`);
  } else {
    const repository = resolve(runDir, state.arms.stock.repository);
    const compile = await runOwnedContainer({ docker, name: `${prefix}-compile`, signal, timeoutMs: 10 * 60 * 1000,
      createArgs: [...containerArgs(state), "-v", `${repository}:/baseline:ro`, image, "sh", "-lc",
        `cp -a /baseline /tmp/preflight && cd /tmp/preflight && ${iconsGoCheck} && ${iconsTest} && git diff --exit-code HEAD -- && test "$(git rev-parse HEAD)" = ${state.source.base_commit} && test -z "$(git remote)" && ! git config --get submodule.webui.url && test "$(git submodule status -- webui | cut -c1)" = - && test -z "$(ls -A webui)" && ${state.submodules!.map(sub => `test -z "$(git -C ${sub.path} remote)" && test "$(git submodule status -- ${sub.path} | cut -c1)" = ' ' && test -z "$(git -C ${sub.path} status --porcelain --untracked-files=all)" && test "$(git -C ${sub.path} rev-parse HEAD)" = ${sub.sha}`).join(" && ")}`] });
    await writeFile(join(runDir, "artifacts/preflight-icons.json"), JSON.stringify(compile, null, 2));
    if (compile.exitCode !== 0) throw new Error(`icons preflight failed: ${compile.stdout.trim()} ${compile.stderr.trim()}`);
  }
  if (state.protected_runtime) await protectedPreflight(docker, runDir, state, signal);
  progress("preflight passed without model inference");
  return image;

}

async function preflight(docker: string, state: RunState, runDir: string): Promise<string> {
  const controller = new AbortController();
  const cancel = () => controller.abort();
  process.once("SIGINT", cancel);
  process.once("SIGTERM", cancel);
  try {
    const imageId = await preflightChecks(docker, state, runDir, controller.signal);
    if (controller.signal.aborted) throw new Error("preflight canceled; no model was launched");
    return imageId;
  } finally {
    process.removeListener("SIGINT", cancel);
    process.removeListener("SIGTERM", cancel);
  }
}

async function preflightRunUnlocked(runDirectory: string, dockerBin = process.env.CODEX_AB_DOCKER_BIN ?? "docker"): Promise<void> {
  const runDir = resolve(runDirectory);
  const state = await readState(runDir);
  if (state.status !== "prepared") throw new Error(`preflight requires a prepared run, got ${state.status}`);
  state.image_id = await preflight(dockerBin, state, runDir);
  await writeState(runDir, state);
}

async function prewarm(docker: string, runDir: string, state: RunState, arm: ArmName, home: string, cache: string, moduleCache: string, signal: AbortSignal): Promise<void> {
  const name = `codex-ab-${state.id}-${arm}-agent-warm`;
  const repo = resolve(runDir, state.arms[arm].repository);
  const bun = resolve(runDir, state.runtime_tools.bun);
  const command = state.profile === "godoxy-icons"
    ? `${iconsGoCheck} && ${iconsTest}`
    : `${prepareAssets(state)} && ${state.criteria ? "true" : `go test ${testPackage(state)} -run '^$'`}`;
  const result = await runOwnedContainer({ docker, name, signal, createArgs: [...containerArgs(state),
    "-v", `${repo}:/workspace`, "-v", `${home}:/home/ubuntu`,
    "-v", `${cache}:/home/ubuntu/.cache/go-build`, "-v", `${moduleCache}:/home/ubuntu/go/pkg`,
    "-v", `${bun}:/usr/local/bin/bun:ro`, imageRef(state), "sh", "-lc", command] });
  if (result.exitCode !== 0) throw new Error(`${arm} cache prewarm failed: ${result.stderr.trim()}`);
  await inspectCandidate(docker, runDir, state, repo, `${arm}-warm-verify`, signal, true, true);
}
async function freezeGraderCaches(runDir: string, state: RunState, arm: ArmName,
  home: string, cache: string, moduleCache: string): Promise<void> {
  const armRoot = join(runDir, "arms", arm);
  await Promise.all([
    cp(cache, join(armRoot, "grader-go-cache"), { recursive: true, force: false }),
    cp(moduleCache, join(armRoot, "grader-go-pkg-cache"), { recursive: true, force: false }),
    ...(state.profile === "godoxy-icons"
      ? []
      : [cp(join(home, ".bun/install/cache"), join(armRoot, "grader-bun-cache"), { recursive: true, force: false })]),
  ]);
}

async function prewarmEvaluatorCaches(docker: string, runDir: string, state: RunState, arm: ArmName,
  signal: AbortSignal): Promise<void> {
  if (!state.acceptance) return;
  const armRoot = join(runDir, "arms", arm);
  const repo = resolve(runDir, state.arms[arm].repository);
  const acceptance = resolve(runDir, state.acceptance!.path);
  const bun = resolve(runDir, state.runtime_tools.bun);
  const cache = join(armRoot, "grader-go-cache");
  const moduleCache = join(armRoot, "grader-go-pkg-cache");
  const bunCache = join(armRoot, "grader-bun-cache");
  const injectAcceptance = `cp --remove-destination /acceptance.go ${acceptanceTarget(state)}`;
  const prepareWorkspace = `cp -a /baseline /tmp/prewarm && cd /tmp/prewarm && ${injectAcceptance}`;
  const command = state.profile === "godoxy-icons"
    ? `${prepareWorkspace} && ${iconsGoCheck} && ${iconsCompile}`
    : `${prepareWorkspace} && ${prepareAssets(state)} && go test ${testPackage(state)} -run '^$'`;
  const dependencyCaches = ["-v", `${moduleCache}:/home/ubuntu/go/pkg`,
    ...(state.profile === "godoxy-icons" ? [] : ["-v", `${bunCache}:/home/ubuntu/.bun/install/cache`])];
  const result = await runOwnedContainer({ docker, name: `codex-ab-${state.id}-${arm}-evaluator-warm`, signal,
    createArgs: [...containerArgs(state), "-v", `${repo}:/baseline:ro`,
      "-v", `${acceptance}:/acceptance.go:ro`, "-v", `${cache}:/home/ubuntu/.cache/go-build`,
      ...dependencyCaches, "-v", `${bun}:/usr/local/bin/bun:ro`,
      imageRef(state), "sh", "-lc", command] });
  if (result.exitCode !== 0) throw new Error(`${arm} evaluator cache prewarm failed: ${result.stderr.trim()}`);
}


function evidence(command: string, started: Date, result: Awaited<ReturnType<typeof exec>>): CommandEvidence {
  return { command, started_at: started.toISOString(), elapsed_ms: result.elapsedMs, exit_code: result.exitCode, stdout: result.stdout, stderr: result.stderr };
}

export async function gradeArm(docker: string, runDir: string, state: RunState, arm: ArmName, patchPath: string, signal: AbortSignal, evaluator = join(runDir, "evaluator", arm)): Promise<ArmResult["grade"]> {
  if (!state.acceptance && !state.criteria) return undefined;

  await checked(["git", "clone", "--no-local", "--no-hardlinks", join(runDir, "seed.git"), evaluator]);
  await checked(["git", "-C", evaluator, "checkout", state.source.base_commit]);
  await checked(["git", "-C", evaluator, "remote", "remove", "origin"]);
  await initializeSubmodules(evaluator, state.submodules ?? []);
  await inspectCandidate(docker, runDir, state, evaluator, `${arm}-grade-verify`, signal, true, false);
  const patchStat = await Bun.file(patchPath).size;
  if (patchStat > 0) await checked(["git", "-C", evaluator, "apply", "--binary", patchPath]);
  await inspectCandidate(docker, runDir, state, evaluator, `${arm}-grade-verify`, signal, true, false);
  const forbiddenChanges = state.criteria?.contract.allowed_paths ? (state.results?.[arm]?.changed_files ?? []).filter(path => !state.criteria!.contract.allowed_paths!.includes(path)) : [];
  if (!state.acceptance || forbiddenChanges.length) {
    const ready: CommandEvidence = { command: "immutable candidate capture and task-required change boundaries", started_at: new Date().toISOString(),
      elapsed_ms: 0, exit_code: forbiddenChanges.length ? 1 : 0, stdout: "", stderr: forbiddenChanges.length ? `Outside task change boundary: ${forbiddenChanges.join(", ")}` : "" };
    const pending: CommandEvidence = { ...ready, command: "semantic checks pending independent judges", exit_code: -1 };
    return { preparation: ready, acceptance: pending, router_suite: pending, elapsed_ms: 0, passed: false };
  }
  const evaluatorAcceptanceTarget = acceptanceTarget(state);
  const injectAcceptance = `cp --remove-destination /acceptance.go ${evaluatorAcceptanceTarget}`;
  const gradeStarted = performance.now();
  const bun = resolve(runDir, state.runtime_tools.bun);
  const bunCache = resolve(runDir, "arms", arm, "grader-bun-cache");
  const moduleCache = resolve(runDir, "arms", arm, "grader-go-pkg-cache");
  const cache = resolve(runDir, "arms", arm, "grader-go-cache");
  let started = new Date();
  const dependencyCaches = ["-v", `${moduleCache}:/home/ubuntu/go/pkg:ro`,
    ...(state.profile === "godoxy-icons" ? [] : ["-v", `${bunCache}:/home/ubuntu/.bun/install/cache:ro`])];
  const preparationResult = await runOwnedContainer({ docker, name: `codex-ab-${state.id}-${arm}-grade-prepare`, signal, createArgs: [...containerArgs(state), "--network", "none", "-v", `${resolve(evaluator)}:/workspace`, "-v", `${cache}:/home/ubuntu/.cache/go-build`, ...dependencyCaches,
    "-v", `${bun}:/usr/local/bin/bun:ro`, "-v", `${resolve(runDir, state.acceptance.path)}:/acceptance.go:ro`, imageRef(state), "sh", "-lc", `${injectAcceptance} && ${state.profile === "godoxy-icons" ? iconsGoCheck : prepareAssets(state)}`] });
  await inspectCandidate(docker, runDir, state, evaluator, `${arm}-grade-verify`, signal, true, false);
  const preparation = evidence(state.profile === "godoxy-icons" ? iconsGoCheck : prepareAssets(state), started, preparationResult);
  if (preparation.exit_code !== 0 || signal.aborted) {
    const skipped = { command: "not run", started_at: new Date().toISOString(), elapsed_ms: 0, exit_code: -1, stdout: "", stderr: signal.aborted ? "grading canceled" : "grading preparation failed" };
    return { preparation, acceptance: skipped, router_suite: skipped, elapsed_ms: Math.round(performance.now() - gradeStarted), passed: false };
  }
  const base = [...containerArgs(state), "--network", "none", "-v", `${resolve(evaluator)}:/workspace`, "-v", `${cache}:/home/ubuntu/.cache/go-build`, ...dependencyCaches, "-v", `${bun}:/usr/local/bin/bun:ro`, imageRef(state)];
  started = new Date();
  const acceptanceCommand = state.profile === "godoxy-icons" ? `go test -json -count=1 -ldflags=-checklinkname=0 -run '^TestABAcceptance' ${iconsPackage}` : `go test -json ${testPackage(state)} -run '^TestABAcceptance' -count=1`;
  const acceptanceResult = await runOwnedContainer({ docker, name: `codex-ab-${state.id}-${arm}-grade`, signal, createArgs: state.profile === "godoxy-icons" ? [...base, "sh", "-lc", acceptanceCommand] : [...base, "go", "test", "-json", testPackage(state), "-run", "^TestABAcceptance", "-count=1"] });
  await inspectCandidate(docker, runDir, state, evaluator, `${arm}-grade-verify`, signal, true, false);
  const expectedTests = acceptanceTestNames(await readFile(join(runDir, state.acceptance.path), "utf8"));
  const acceptance = evidence(acceptanceCommand, started, acceptanceResult);
  acceptance.validation_error = acceptanceExecutionError(acceptance.stdout, expectedTests);
  if (signal.aborted) {
    const skipped = { command: "not run", started_at: new Date().toISOString(), elapsed_ms: 0, exit_code: -1, stdout: "", stderr: "grading canceled" };
    return { preparation, acceptance, router_suite: skipped, elapsed_ms: Math.round(performance.now() - gradeStarted), passed: false };
  }
  started = new Date();
  const suiteCommand = state.profile === "godoxy-icons" ? iconsTest.replace("go test", "go test -json") : `go test -json ${testPackage(state)} -count=1`;
  const suiteResult = await runOwnedContainer({ docker, name: `codex-ab-${state.id}-${arm}-grade-suite`, signal, createArgs: state.profile === "godoxy-icons" ? [...base, "sh", "-lc", suiteCommand] : [...base, "go", "test", "-json", testPackage(state), "-count=1"] });
  await inspectCandidate(docker, runDir, state, evaluator, `${arm}-grade-verify`, signal, true, false);
  const routerSuite = evidence(suiteCommand, started, suiteResult);
  routerSuite.validation_error = acceptanceExecutionError(routerSuite.stdout, expectedTests);
  const requiredElapsedMs = Math.round(performance.now() - gradeStarted);
  // Two full package runs need more than the previous one-minute budget.
  const repeatCommand = `${suiteCommand.replace("-count=1", "-count=2")} -timeout=180s`;

  started = new Date();
  let supplementalInfrastructureError: string | undefined;
  let supplementalRepeat: CommandEvidence;
  try {
    const repeatResult = await runOwnedContainer({
      docker, name: `codex-ab-${state.id}-${arm}-supplemental-repeat`, signal,
      timeoutMs: 210_000,
      createArgs: [...containerArgs(state), "--network", "none",
        "-v", `${resolve(evaluator)}:/workspace:ro`,
        "-v", `${cache}:/home/ubuntu/.cache/go-build`,
        ...dependencyCaches, "-v", `${bun}:/usr/local/bin/bun:ro`, imageRef(state), "sh", "-lc", repeatCommand],
    });
    supplementalRepeat = evidence(repeatCommand, started, repeatResult);
    supplementalRepeat.validation_error = acceptanceExecutionError(supplementalRepeat.stdout, expectedTests);
    await inspectCandidate(docker, runDir, state, evaluator, `${arm}-supplemental-verify`, signal, true, false);
  } catch (error) {
    supplementalInfrastructureError = String(error);
    supplementalRepeat = { command: repeatCommand, started_at: started.toISOString(),
      elapsed_ms: Date.now() - started.getTime(), exit_code: -1, stdout: "", stderr: String(error),
      validation_error: "supplemental infrastructure failure; required checks retained" };
  }

  const evaluatorError = evaluatorCompatibilityError(acceptance.stdout) ?? evaluatorCompatibilityError(routerSuite.stdout);
  return { preparation, acceptance, router_suite: routerSuite, evaluator_error: evaluatorError, supplemental_repeat: supplementalRepeat, supplemental_infrastructure_error: supplementalInfrastructureError, elapsed_ms: requiredElapsedMs, passed: !evaluatorError && preparation.exit_code === 0 && acceptance.exit_code === 0 && routerSuite.exit_code === 0 && !acceptance.validation_error && !routerSuite.validation_error };
}

async function runArm(docker: string, runDir: string, state: RunState, arm: ArmName, home: string, output: string, cache: string, moduleCache: string, task: string, signal: AbortSignal): Promise<ArmResult> {
  const name = `codex-ab-${state.id}-${arm}`;
  const repository = resolve(runDir, state.arms[arm].repository);
  const stdoutPath = join(output, "codex.jsonl");
  const stderrPath = join(output, "codex.stderr");
  const patchPath = join(output, "changes.patch");
  const started = new Date();
  progress(`${arm}: agent started`);
  let result: ExecResult | undefined;
  let lifecycleError: string | undefined;
  const exportArgs = arm === "current" && state.mekugi_exports
    ? ["--capture-output=/mekugi-exports/capture.jsonl", "--metrics-output=/mekugi-exports/metrics.json"] : [];
  const exportMount = exportArgs.length ? ["-v", `${join(output, "mekugi")}:/mekugi-exports`] : [];
  if (exportArgs.length) await mkdir(join(output, "mekugi"), { recursive: true, mode: 0o700 });
  const protectedArm = arm === "current" && state.protected_runtime;
  const runtime = join(output, "runtime");
  const ownedPaths = [repository, home, cache, moduleCache, join(output, "mekugi"), runtime];
  if (protectedArm) await mkdir(runtime, { recursive: true });
  const codexLauncher = arm === "current" && state.execution.current_launcher === "mekugi" ? ["mekugi", ...(state.mekugi_flags ?? []), ...exportArgs, "codex"] : ["codex"];
  const launcher = arm === "current" || state.comparison === "same-setup" ? ["mise", "exec", "--", ...codexLauncher] : ["codex"];
  try {
    if (protectedArm) await executorOwnership(docker, state, `${name}-own`, ownedPaths, false);
    result = await runOwnedContainer({ docker, name, signal, stdin: task, stdoutFile: stdoutPath, stderrFile: stderrPath, timeoutMs: state.timeout_seconds * 1000, createArgs: [...containerArgs(state), "-i", "-e", "PATH=/home/ubuntu/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/go/bin",
      "-v", `${repository}:/workspace`, "-v", `${home}:/home/ubuntu`, "-v", `${cache}:/home/ubuntu/.cache/go-build`, "-v", `${moduleCache}:/home/ubuntu/go/pkg`, ...currentSetupMounts(runDir, state, arm), ...exportMount,
      ...(protectedArm ? [...protectedArgs(runDir, state, runtime), "-v", `${join(moduleCache, "mod")}:/go/pkg/mod:ro`] : []),
      imageRef(state), ...launcher, "exec", "--json", "--color", "never", "--dangerously-bypass-hook-trust", "-C", "/workspace", "--model", state.execution.model,
      "-c", `model_reasoning_effort=${JSON.stringify(state.execution.reasoning_effort)}`, "-c", `service_tier=${JSON.stringify(state.execution.service_tier)}`, "-c", 'approval_policy="never"', "-c", 'sandbox_mode="danger-full-access"', "-"] });
  } catch (error) {
    lifecycleError = error instanceof Error ? error.message : String(error);
    if (error instanceof OwnedContainerError && error.result) result = error.result;
  }
  if (protectedArm) {
    try { await executorOwnership(docker, state, `${name}-restore`, ownedPaths, true); }
    catch (error) { lifecycleError = `${lifecycleError ?? ""} ${String(error)}`.trim(); }
  }
  const finishedAt = new Date().toISOString();
  progress(`${arm}: agent stopped after ${Math.round((result?.elapsedMs ?? 0) / 1000)}s${lifecycleError ? ` (${lifecycleError})` : ""}`);
  return {
    arm,
    anonymous_id: arm === "stock" ? "candidate-1" : "candidate-2",
    container: name,
    started_at: started.toISOString(),
    finished_at: finishedAt,
    agent_elapsed_ms: result?.elapsedMs ?? 0,
    exit_code: result?.exitCode ?? -1,
    timed_out: result?.timedOut ?? false,
    canceled: result?.canceled === true || signal.aborted,
    patch_path: patchPath.slice(runDir.length + 1),
    stdout_path: stdoutPath.slice(runDir.length + 1),
    stderr_path: stderrPath.slice(runDir.length + 1),
    changed_files: [],
    head_after_agent: "",
    lifecycle_error: lifecycleError,
  };
}

async function collectArm(docker: string, runDir: string, state: RunState, arm: ArmName, result: ArmResult): Promise<void> {
  const repository = resolve(runDir, state.arms[arm].repository);
  const patchPath = join(runDir, result.patch_path);
  try {
    // Cleanup has completed before collection. Use a fresh signal so canceled
    // inference can still preserve its available patch without launching models.
    await inspectCandidate(docker, runDir, state, repository, `${arm}-capture`, new AbortController().signal, false, false, dirname(patchPath));
    for (const path of [patchPath, join(dirname(patchPath), "result.json")]) {
      if (!(await lstat(path)).isFile()) throw new Error("capture artifact must be a regular file");
    }
    const metadata = JSON.parse(await readFile(join(dirname(patchPath), "result.json"), "utf8")) as { changed_files?: unknown; head_after_agent?: unknown };
    if (!Array.isArray(metadata.changed_files) || metadata.changed_files.some(value => typeof value !== "string")
      || typeof metadata.head_after_agent !== "string" || !/^[0-9a-f]{40}$/.test(metadata.head_after_agent)) throw new Error("invalid capture metadata");
    result.changed_files = metadata.changed_files;
    result.head_after_agent = metadata.head_after_agent;
  } catch (error) {
    result.collection_error = error instanceof Error ? error.message : String(error);
    // Do not follow or overwrite a candidate-created capture symlink on failure.
    progress(`${arm}: inference evidence persisted but patch collection failed: ${result.collection_error}`);
  }
}

export async function runPairUnlocked(options: RunOptions): Promise<RunState> {
  const runDir = resolve(options.runDir);
  const state = await readState(runDir);
  if (state.status !== "prepared") throw new Error(`run is ${state.status}; prepare a new run instead of resuming or restarting it`);
  if (!state.acceptance && !state.criteria) throw new Error("run has no evaluator contract; prepare with --criteria or --acceptance");
  if (state.criteria && options.arm) throw new Error("semantic grading requires both arms for independent reversed-order assessment");
  const docker = options.dockerBin ?? process.env.CODEX_AB_DOCKER_BIN ?? "docker";
  state.image_id = await preflight(docker, state, runDir);
  await writeState(runDir, state);
  const controller = new AbortController();
  if (options.signal?.aborted) controller.abort();
  const externalCancel = () => controller.abort();
  options.signal?.addEventListener("abort", externalCancel, { once: true });
  const selectedArms: ArmName[] = options.arm ? [options.arm] : arms;
  const cancel = () => controller.abort();
  process.once("SIGINT", cancel);
  process.once("SIGTERM", cancel);
  try {
    const auth = resolve(options.authFile);
    const authMode = (await import("node:fs/promises")).stat(auth).then(s => s.mode & 0o777);
    if ((await authMode) & 0o077) throw new Error("auth file must not be accessible by group or others (expected mode 0600)");
    const setupResults = await Promise.allSettled(selectedArms.map(async arm => [arm, await setupArm(runDir, state, arm, auth)] as const));
    const setupFailure = setupResults.find(result => result.status === "rejected");
    if (setupFailure?.status === "rejected") throw setupFailure.reason;
    const setups = Object.fromEntries(setupResults.map(result => (result as PromiseFulfilledResult<readonly [ArmName, Awaited<ReturnType<typeof setupArm>>]>).value)) as Partial<Record<ArmName, Awaited<ReturnType<typeof setupArm>>>>;
    if (controller.signal.aborted) throw new Error("canceled during private arm setup; no model was launched");
    state.status = "running";
    state.results = {};
    state.selected_arms = selectedArms;
    await writeState(runDir, state);
    progress(options.arm ? `prewarming the selected ${options.arm} arm` : "prewarming identical Go targets for both arms");
    const warmed = await Promise.allSettled(selectedArms.map(arm => prewarm(docker, runDir, state, arm, setups[arm]!.home, setups[arm]!.cache, setups[arm]!.moduleCache, controller.signal)));
    const warmFailure = warmed.find(result => result.status === "rejected");
    if (warmFailure?.status === "rejected") throw warmFailure.reason;
    if (controller.signal.aborted) throw new Error("canceled during dependency prewarm; no agent was launched");
    progress("preparing evaluator-only dependency caches before inference");
    await Promise.all(selectedArms.map(arm => freezeGraderCaches(runDir, state, arm,
      setups[arm]!.home, setups[arm]!.cache, setups[arm]!.moduleCache)));
    const evaluatorWarmed = await Promise.allSettled(selectedArms.map(arm =>
      prewarmEvaluatorCaches(docker, runDir, state, arm, controller.signal)));
    const evaluatorWarmFailure = evaluatorWarmed.find(result => result.status === "rejected");
    if (evaluatorWarmFailure?.status === "rejected") throw evaluatorWarmFailure.reason;
    if (controller.signal.aborted) throw new Error("canceled during evaluator dependency prewarm; no agent was launched");
    await verifyPreparedInputs(runDir, state);
    const task = await readFile(join(runDir, state.task.path), "utf8");
    if (controller.signal.aborted) throw new Error("canceled while reading the task; no agent was launched");
    for (const arm of selectedArms) {
      const repo = resolve(runDir, state.arms[arm].repository);
      await inspectCandidate(docker, runDir, state, repo, `${arm}-launch-verify`, controller.signal, true, true);
    }
    const launchTime = new Date().toISOString();
    state.arm_attempts = Object.fromEntries(selectedArms.map(arm => [arm, {
      codex_home: `arms/${arm}/home/ubuntu/.codex`,
      container: `codex-ab-${state.id}-${arm}`,
      started_at: launchTime,
      status: "started",
    }])) as RunState["arm_attempts"];
    await writeState(runDir, state);
    const settled = await Promise.allSettled(selectedArms.map(arm => runArm(docker, runDir, state, arm, setups[arm]!.home, setups[arm]!.output, setups[arm]!.cache, setups[arm]!.moduleCache, task, controller.signal)));
    settled.forEach((item, index) => {
      const arm = selectedArms[index]!;
      const attempt = state.arm_attempts![arm]!;
      attempt.finished_at = new Date().toISOString();
      if (item.status === "fulfilled") state.results![arm] = item.value;
      else {
        attempt.status = "failed";
        attempt.error = String(item.reason);
        const message = `${arm}: failed to collect result: ${String(item.reason)}`;
        state.error = state.error ? `${state.error}; ${message}` : message;
        progress(message);
      }
      if (item.status === "fulfilled") attempt.status = "stopped";
    });
    await writeState(runDir, state);
    const collected = await Promise.allSettled(selectedArms.map(async arm => {
      const result = state.results?.[arm];
      if (result && !result.lifecycle_error) await collectArm(docker, runDir, state, arm, result);
    }));
    const collectionFailure = collected.find(result => result.status === "rejected");
    if (collectionFailure?.status === "rejected") state.error = String(collectionFailure.reason);
    await writeState(runDir, state);
    if (!controller.signal.aborted && selectedArms.every(arm => state.results?.[arm] && !state.results[arm]!.lifecycle_error && !state.results[arm]!.collection_error)) {
      progress(`${options.arm ? "selected agent" : "both agents"} stopped; starting evaluator-only grading`);
      const graded = await Promise.allSettled(selectedArms.map(async arm => {
        const result = state.results![arm]!;
        result.grade = await gradeArm(docker, runDir, state, arm, join(runDir, result.patch_path), controller.signal);
        if (result.grade?.evaluator_error) {
          result.lifecycle_error = result.grade.evaluator_error;
          state.error = `${arm}: ${result.grade.evaluator_error}`;
        }
        if (result.grade?.supplemental_infrastructure_error) {
          result.lifecycle_error = result.grade.supplemental_infrastructure_error;
          state.error = `${arm}: supplemental infrastructure failed: ${result.lifecycle_error}`;
        }
        progress(`${arm}: grading ${state.criteria && !state.acceptance ? "prepared for independent semantic assessment" : result.grade ? (result.grade.passed ? "passed" : "failed") : "not configured"}`);
      }));
      const gradeFailure = graded.find(result => result.status === "rejected");
      if (gradeFailure?.status === "rejected") throw gradeFailure.reason;
    }
    for (const result of Object.values(state.results)) {
      if (result?.collection_error) state.error = state.error ? `${state.error}; ${result.collection_error}` : result.collection_error;
    }
    state.status = !controller.signal.aborted && selectedArms.every(arm => state.results?.[arm] && !state.results[arm]!.lifecycle_error && !state.results[arm]!.collection_error && state.results[arm]!.grade) ? "complete" : "partial";
    await writeState(runDir, state);
    return state;
  } catch (error) {
    state.status = "partial";
    state.error = error instanceof Error ? error.message : String(error);
    await writeState(runDir, state);
    throw error;
  } finally {
    options.signal?.removeEventListener("abort", externalCancel);
    process.removeListener("SIGINT", cancel);
    process.removeListener("SIGTERM", cancel);
  }
}

export async function preflightRun(runDirectory: string, dockerBin = process.env.CODEX_AB_DOCKER_BIN ?? "docker"): Promise<void> {
  return withRunLock(resolve(runDirectory), () => preflightRunUnlocked(runDirectory, dockerBin));
}

export async function runPair(options: RunOptions): Promise<RunState> {
  return withRunLock(resolve(options.runDir), () => runPairUnlocked(options));
}
